[package]
name = "label_studio_yolo_datasets_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive", "cargo"] }
zip = "2.2.2"
walkdir = "2.3.2"